donMaxsulot/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings

from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]
    # re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import home, signup_user, logout_user, login_user, base, editItem, agentTake, editAgent, delete, deleteHome, editHome, payToAgent, deleteBase, baza, editBaza, deleteBaza, addAgent, deleteAgent, addRealBazaWhenHaveProducts, addMoneyWhenTakeMoney, deleteAddMoneyWhenTakeMoney, returnProduct, returnProductForSavod

urlpatterns = [
    path('', home, name='home'),
    path('delete/<int:home_id>', deleteHome, name='deleteHome'),
    path('<int:home_id>', editHome, name='editHome'),
    # Note Auth
    path('signup/', signup_user, name='signup'),
    path('logout/', logout_user, name='logout'),
    path('login/', login_user, name='login'),
    # Note Baza
    path('baza/', baza, name='baza'),
    path('baza/<int:get_id>', editBaza, name='editBaza'),
    path('baza/delete/<int:get_id>', deleteBaza, name='deleteBaza'),
    path('baza/add/<int:product_id>', addRealBazaWhenHaveProducts, name='addRealBazaWhenHaveProducts'),
    # Note bozor
    path('bozor/', base, name='base'),
    path('bozor/addMoney', addMoneyWhenTakeMoney, name='addMoneyWhenTakeMoney'),
    path('bozor/addMoney/delete/<int:block_id>', deleteAddMoneyWhenTakeMoney, name='deleteAddMoneyWhenTakeMoney'),
    path('bozor/<int:product_id>', editItem, name='editItem'),
    path('bozor/delete/<int:product_id>', deleteBase, name='deleteBase'),
    path('bozor/return/<int:returnProduct_id>', returnProduct, name='returnProduct'),
    # Savdo tochkasi
    path('savdo/', agentTake, name='agentTake'),
    path('savdo/<int:agent_id>', editAgent, name='editAgent'),
    path('savdo/return/<int:returnProduct_id>', returnProductForSavod, name='returnProductForSavod'),
    path('savdo/delete/<int:agent_id>', delete, name='delete'),
    path('savdo/payToAgent', payToAgent, name='payToAgent'),
    path('addAgent/', addAgent, name='addAgent'),
    path('addAgent/deleteAgent/<int:deleteAgent_id>', deleteAgent, name='deleteAgent'),
]

home/models.py
from django.db import models

class Home(models.Model):
    img = models.ImageField(null=True, blank=True, upload_to='images/')
    title = models.CharField(max_length=100)
    des = models.TextField(blank=True)
    price = models.IntegerField(default=0)
    showToAgent = models.IntegerField(default=0)

# Bozor
class mainBase(models.Model):
    typeOfProduct = models.TextField()
    kg = models.FloatField(default=0)
    insidePrice = models.IntegerField(default=0)
    outsidePrice = models.IntegerField(default=0)
    totalSum = models.IntegerField(default=0, blank=True)
    date = models.DateField(null=True, auto_now_add=True)
    byWhom = models.TextField(default="")
    changed = models.BooleanField(default=False)

    debt = models.BooleanField(null=True, default=False)
    lastLendDebt = models.IntegerField(null=True, default=0)
    qarzSum = models.IntegerField(null=True, default=0)
    oxirgiQarzBerganVaqti = models.DateField(null=True, auto_now_add=False)
    totalLend = models.IntegerField(null=True, default=0)

# Savdo tochkasi
class Qarz(models.Model):
    typeOfProduct = models.TextField(null=True)
    kg = models.FloatField(null=True, default=0)
    orginalPrice = models.IntegerField(null=True, default=0)
    price = models.IntegerField(null=True, default=0)
    totalSum = models.IntegerField(default=0, blank=True)
    date = models.DateField(null=True, auto_now_add=True)
    afterCreateDate = models.DateField(null=True, auto_now_add=True)
    byWhom = models.TextField(null=True, default="")
    changed = models.BooleanField(null=True, default=False)
    debt = models.BooleanField(null=True, default=False)

    qarzSum = models.IntegerField(null=True, default=0)
    oxirgiQarzBerganVaqti = models.DateField(null=True, auto_now_add=False)
    afterCreateDate = models.DateField(null=True, auto_now_add=True)
    totalLend = models.IntegerField(null=True, default=0)

class PayAgent(models.Model):
    who = models.TextField(default='')
    payAgent = models.IntegerField(null=True, default=0)
    lastPayAgent = models.IntegerField(null=True, default=0)
    date = models.DateField(null=True, auto_now_add=True)

class TakeMoneyFromBazar(models.Model):
    TakeMoney = models.IntegerField(null=True, default=0)
    date = models.DateField(null=True, auto_now_add=True)
    who = models.TextField(default='')

# Real Baza
class Baza(models.Model):
    typeOfProduct = models.TextField()
    kgOrg = models.FloatField(default=0)
    kg = models.FloatField(default=0)
    price = models.IntegerField(default=0)
    totalSum = models.IntegerField(default=0, blank=True)
    date = models.DateField(null=True, auto_now_add=True)
    byWhom = models.TextField(default="")
    debt = models.BooleanField(null=True, default=False)
    changed = models.BooleanField(null=True, default=False)
    debtSum = models.IntegerField(null=True, default=0)
    
    lastLendDebt = models.IntegerField(null=True, default=0)
    oxirgiQarzBerganVaqti = models.DateField(null=True, auto_now_add=False)
    totalLend = models.IntegerField(null=True, default=0)

class Admins(models.Model):
    name = models.TextField()

class Agents(models.Model):
    name = models.TextField()

home/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User  # admin paneldagi user modeli
from django.contrib import messages
from django.db import IntegrityError  # Pythonda mavjud bo'lmagan xatolik
# authenticate->signin qismini tekshiradi
from django.contrib.auth import login, logout, authenticate
from django.http import HttpResponse, JsonResponse
from .models import Home, mainBase, Qarz, PayAgent, Baza, Agents, Admins, TakeMoneyFromBazar
from .forms import Basee, QarzForm, InputQarzForm, HomeForm, PayAgentForm, LendDebt, BazaForm, LendDebtForBaza, AgentsForm, TakeMoneyFromBazarForm
from datetime import date, datetime, timedelta


admins = ['aslamjon', 'qobiljon']
agentsList = []


def checkIsAdmin(request, html, sendObjToAdmin, sendObjToAnonimUser):
    getAdmins = Admins.objects.all()
    global admins
    admins = []
    for i in getAdmins:
        admins.append(i.name)
    if request.user.username in admins:
        sendObjToAdmin['isAdmin'] = True
        return render(request, html, sendObjToAdmin)
    else:
        if request.user.username in agentsList:
            sendObjToAnonimUser['isAgent'] = True
            return render(request, html, sendObjToAnonimUser)
        sendObjToAnonimUser['isAdmin'] = False
        return render(request, html, sendObjToAnonimUser)


def home(request):
    getAgents = Agents.objects.all()
    for i in getAgents:
        agentsList.append(i.name)
    getHome = Home.objects.all()
    if (request.method == 'GET'):
        sentObjToTemplate = {'home': getHome, 'homeForm': HomeForm}

        return checkIsAdmin(request, 'html/index.html', sentObjToTemplate, sentObjToTemplate)
    elif (request.method == 'POST'):
        createBlogToHome = HomeForm(request.POST, request.FILES)
        if createBlogToHome.is_valid():
            createBlogToHome.save()
        # getHome
        # id yordamida home dagi cardlarni o'zgartirish kerak
        return redirect('home')
    else:
        sentObjToTemplate = {'home': getHome, 'homeForm': HomeForm}
        return checkIsAdmin(request, 'html/index.html', sentObjToTemplate, sentObjToTemplate)


def editHome(request, home_id):
    product = get_object_or_404(Home, pk=home_id)
    if request.method == "GET":
        form = HomeForm(instance=product)
        sentToHomeEdit = {
            'form': form,
            'product': product
        }
        return checkIsAdmin(request, 'html/editHome.html', sentToHomeEdit, sentToHomeEdit)
    if (request.method == 'POST'):
        form = HomeForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            return redirect('home')

    else:
        return redirect('home')


def deleteHome(request, home_id):
    blog = get_object_or_404(Home, pk=home_id)
    if request.method == 'POST':
        blog.delete()
        return redirect('home')


def signup_user(request):
    if request.method == 'GET':
        user = UserCreationForm()  # signup
        return render(request, 'html/signUp.html', {'user': user})
    else:
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.create_user(
                    request.POST['username'], password=request.POST['password1'])
                user.save()
                login(request, user)
                # redirect render dan farqi unga funksiyalarni kiritsa bo'ladi.
                return redirect('home')
            except IntegrityError:
                return render(request, 'html/signUp.html', {'user': UserCreationForm(), 'error': 'Username sizdan oldin band qilngan'})

        else:
            return render(request, 'html/signUp.html', {'user': UserCreationForm(), 'error': 'Sizning parolingiz bir xil emas'})


def login_user(request):
    if request.method == 'GET':
        user = AuthenticationForm()
        return render(request, 'html/login.html', {'user': user})
    else:
        user = authenticate(
            request, username=request.POST['username'], password=request.POST['password'])
        if user is None:
            return render(request, 'html/login.html', {'user': AuthenticationForm(), 'error': "username yoki parol xato iltimos qytadan urunib ko'ring"})
        else:
            login(request, user)
            return redirect('home')


def logout_user(request):
    if request.method == 'POST':
        logout(request)
        return redirect('home')


# @login_required
#  ************ Baza ******************
def baza(request):
    def getDataFromBaza():
        return Baza.objects.all()
    
    sendToTemplateForAdmin = {
        'bazaForm': BazaForm,
        'getBaza': getDataFromBaza(),
        'residue': 0
    }
    for item in getDataFromBaza():
        sendToTemplateForAdmin['residue'] += (item.kgOrg * item.price)
        
    
    sendToTemplateForAdmin['residue'] = int(sendToTemplateForAdmin['residue'])
    
    if (request.method == 'GET'):
        return checkIsAdmin(request, 'html/realBaza.html',sendToTemplateForAdmin, {})
    elif request.method == 'POST':
        saveData = BazaForm(request.POST)
        if saveData.is_valid():
            saveData.save()
            getBase = getDataFromBaza()
            searchRes = getBase[len(getBase)-1]
            if searchRes.debt and searchRes.debtSum == 0:
                searchRes.debtSum = searchRes.totalSum
            searchRes.kgOrg = searchRes.kg
            searchRes.save()
            return redirect('baza')
        else:
            getData = sendToTemplateForAdmin()
            getData['error'] = "Ma'lumot kiritishda xotolik yuz berdi" 
            return checkIsAdmin(request, 'html/realBaza.html', getData, {})


def editBaza(request, get_id):
    product = get_object_or_404(Baza, pk=get_id)
    if request.method == "GET":
        form = BazaForm(instance=product)
        sendToTemplate = {
            'product': product, 'form': form, 'LendDebtForBaza': LendDebtForBaza,
            'formId': get_id
        }
        return checkIsAdmin(request, 'html/editRealBaza.html', sendToTemplate, {"a": 'a'})
    elif request.method == 'POST':
        if len(request.POST) < 4:
            form = LendDebtForBaza(request.POST, instance=product)
            
            sendToTemplate = {
                'product': product, 'LendDebt': LendDebtForBaza,
                'error': '', 'formId': get_id
            }
            if form.is_valid():
                product.debtSum -= int(request.POST.get('lastLendDebt'))
                product.totalLend += int(request.POST.get('lastLendDebt'))
                form.save()
                product.save()

                return redirect('baza')
            else:
                sendToTemplate['error'] = "Ma'lumot to'liq kiritilmagan qaydadan urinib ko'ring"
                return checkIsAdmin(request, 'html/editRealBaza.html', sendToTemplate, {"a": 'a'})
        else:
            if product.kg == product.kgOrg and not product.changed:
                product.kgOrg = float(request.POST.get('kg'))
            form = BazaForm(request.POST, instance=product)
            if form.is_valid():
                form.save()
                product.changed = True
                product.save()
                return redirect('baza')
    else:
        return redirect('baza')


def deleteBaza(request, get_id):
    product = get_object_or_404(Baza, pk=get_id)
    if request.method == 'POST':
        product.delete()
        return redirect('baza')

#  ************ Bozor ******************
def base(request):
    def getTotalRes(first,secound=0):
        totalRes = {
            "priceSum": 0,
            'rest':0,
            "kgSum": 0,
            "debtSum": 0,
            "expectedBenefit": 0,
            "pratsent": 0
        }
        for i in range(len(first)):
            totalRes['priceSum'] += (first[i].kg * first[i].outsidePrice)
            totalRes['kgSum'] += first[i].kg
            totalRes['debtSum'] += first[i].totalLend
            totalRes['expectedBenefit'] += ((first[i].kg * first[i].outsidePrice) -
                                            (first[i].kg * first[i].insidePrice))
            totalRes['pratsent'] += (first[i].kg * first[i].outsidePrice)
        totalRes['priceSum'] = int(totalRes['priceSum'])
        totalRes['debtSum'] = int(totalRes['debtSum'])
        totalRes['expectedBenefit'] = int(totalRes['expectedBenefit'])
        totalRes['pratsent'] = int(totalRes['pratsent'])
        if not secound == 0:
            for item in secound:
                totalRes['rest'] += item.TakeMoney
            totalRes['rest'] = totalRes['priceSum'] - totalRes['rest']
        return totalRes
    if (request.method == 'GET'):
        getBase = mainBase.objects.all()
        getDataFromBaza = Baza.objects.all()
        if request.GET.get('search'):
            sendSearch = getBase.filter(
                byWhom__startswith=request.GET.get('search'))
            return checkIsAdmin(request, 'html/baza.html',
                                {'baza':getDataFromBaza ,'who': sendSearch[0].byWhom, 'totalData': getTotalRes(sendSearch, TakeMoneyFromBazar.objects.all()), 'base': Basee, 'getBase': sendSearch, 'is_admin': True}, {'is_admin': False})
        else:
            return checkIsAdmin(request, 'html/baza.html',
                                {'TakeMoneyFromBazarForm':TakeMoneyFromBazarForm,'baza':getDataFromBaza ,'totalData': getTotalRes(getBase, TakeMoneyFromBazar.objects.all()), 'base': Basee, 'getBase': getBase, 'is_admin': True}, {'is_admin': False})

    elif (request.method == 'POST'):
        saveData = Basee(request.POST)
        getAllData = mainBase.objects.all()

        getDataFromBaza = Baza.objects.all()
        filterBazaForFindingPrice = getDataFromBaza.filter(typeOfProduct__exact=request.POST.get('typeOfProduct'))

home/templates/html/agentTake.html
{% extends 'html/base.html' %}
{% load static %}
{% load indexObj %}
{% block title %}Agents{% endblock %}

{% block content %}
<div class="agentTake base containerCustom">
    {% if user.is_authenticated and isAdmin %}
    <div class="text-danger mb-2">{{error}}</div>
    <button type="button" class="btn btn-success fs-20" data-toggle="modal" data-target="#myModal">
        +
    </button> 
    {% if who %}
    <button type="button" class="btn btn-dark" data-toggle="modal" data-target="#payToAgent">
        Agentga pul to'lash
    </button>
    <div class="modal baseModal" id="payToAgent">
        <div class="modal-dialog">
            <div class="modal-content">
                <!-- Modal Header -->
                <div class="modal-header">
                    <h4 class="modal-title">Agentga pul to'lash</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                    <form id="payAgentForm" action="{% url 'payToAgent' %}" method="POST">
                        {% csrf_token %}
                        {{payAgent.who}}
                        {{payAgent.payAgent}}

                        <button type="button" id="payAgentSubBtn" class="btn btn-outline-dark">Saqlash</button>
                    </form>
                    <script>
                        id_who.value = "{{ who }}";
                        id_payAgent.value = '';
                    </script>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
    <!-- The Modal -->
    <div class="modal baseModal" id="myModal">
        <div class="modal-dialog">
            <div class="modal-content">
                <!-- Modal Header -->
                <div class="modal-header">
                    <h4 class="modal-title">Bazaga ma'lumot kiritish</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                    <form id="enterForm" action="{% url 'agentTake' %}" method="POST">
                        {% csrf_token %}
                        <label for="id_typeOfProduct">Maxsulot turi</label><br>
                        
                        {{qarzForm.typeOfProduct}}
                        <!-- <label for="id_kg">Kg</label><br> -->
                        {{qarzForm.kg}}
                        <!-- <label for="id_price">Sotilayotgan narxi</label><br> -->
                        {{qarzForm.price}}
                        <!-- <label for="id_totalSum">To'liq summasi</label><br> -->
                        {{qarzForm.totalSum}}
                        <label for="id_byWhom" class="">Kim tomonidan?</label><br>
                        {{qarzForm.byWhom}}
                        <div class="d-flex justify-content-between mt-2">
                            <div class="custom-control custom-switch">
                                {{qarzForm.debt}}
                                <label for="id_debt" class="custom-control-label">Yuk qarzga berilganmi?</label>
                            </div>
                            <button type="button" id="subBtn" class="btn btn-outline-dark">Jo'natish</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script>
        if (id_typeOfProduct.children.length == 0) {
            id_typeOfProduct.innerHTML = `<option value="" disabled selected hidden>Bazada ma'lumot kiritilmagan !!!</option>`
        }
        id_kg.value = '';
        id_price.value = '';
        id_totalSum.value = '';
    </script>

    <!-- Search -->
    <div class="mt-3">
        <form class="" action="{% url 'agentTake' %}" method="GET">
            <div class="d-flex">
                <input class="form-control me-2" name="search" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success ml-2" type="submit">Search</button>
            </div>
            <div class="custom-control custom-switch mt-1">
                <input type="checkbox" name="checkbox" class="custom-control-input" id="switch111">
                <label class="custom-control-label" for="switch111">Bir oylik malumotni ko'rish</label>
            </div>
        </form>
    </div>
    {% length getAgentsData as len %}
    {% if not len == 0 %}
    <div class="outAgentTabel">
        <table class="agentTabel baseTabel">
            <tr>
                <th>Kim tomonidan</th>
                <th>Maxsulot turi</th>
                <th>Kg</th>
                <th>Asil narxi</th>
                <th>Sotilayotgan narxi</th>
                <th>To'liq summasi</th>
                <th>Vaqti</th>
                <th>oxirgi bergan qarxi</th>
                <th>Vaqti</th>
            </tr>

            {% for index in range %}
            {% my_tag getAgentsData index as obj %}
            {% my_tag getInputQarz index as obj2 %}
            <tr>
                <td class="">
                    <a class="openEdit text-capitalize" href="{% url 'editAgent' obj.id %}">{{obj.byWhom}}</a>
                </td>
                <td>{{obj.typeOfProduct}}</td>
                <td><span class="">{{obj.kg}}</span> kg</td>
                <td><span class="numMusk">{{obj.orginalPrice}}</span> so'm</td>
                <td><span class="numMusk">{{obj.price}}</span> so'm</td>
                <td>{% if obj.debt == True %}
                    <span class="numMusk text-danger">{{obj.totalSum}}</span> so'm
                    {% else %}
                    <span class="numMusk">{{obj.totalSum}}</span> so'm
                    {% endif %}
                </td>
                <td>{{obj.date}}</td>
                <td>{% filterSth obj2.qarzSum 0 as qarzSumResult %}
                    {% if not qarzSumResult == '' %}
                    <span class="numMusk">{{qarzSumResult}}</span> so'm
                    {% endif %}
                </td>
                <td>{% filterDate obj2.oxirgiQarzBerganVaqti as fDate %}{{fDate}}</td>
            </tr>
            {% endfor %}
        </table>
    </div>
    <div class="outTotalAgent">
        <table class="TotalAgentTabel baseTabel">
            <tr>
                <th>Sotilgan yuklar summasi</th>
                <th>Sotilgan yuklar kg</th>
                <th>Qarzlar</th>
                <th>To'langan Qarzlar</th>
                <th>Kutilayotgan foyda</th>
                <th>Sotilgan yukning 5 % summasi</th>
            </tr>
            <tr>
                <td><span class="numMusk">{{totalRes.priceSum}}</span> so'm</td>
                <td><span class="">{{totalRes.kgSum}}</span> kg</td>
                <td><span class="numMusk text-danger">{{totalRes.debtSum}}</span> so'm</td>
                <td><span class="numMusk text-success">{{totalRes.payDebtSum}}</span> so'm</td>
                <td><span class="numMusk bd-green">{{totalRes.expectedBenefit}}</span> so'm</td>
                <td>
                    {% if who %}
                    <a class="text-decoration-none" href="{% url 'payToAgent' %}">
                        <span class="numMusk">{% fivePre totalRes.pratsent %}</span> so'm
                    </a>
                    {% else %}
                    <span class="numMusk">{% fivePre totalRes.pratsent %}</span> so'm
                    {% endif %}
                </td>
            </tr>
        </table>
    </div>
    {% else %}
    <div class="text-primary mt-3">Bazaga ma'lumot kiritilmaganligi uchun jadval vaqtincha sizga ko'rinmaydi</div>
    {% endif %}
    {% else %}
    <div class="text-danger">Bu bo'limga vaqat admin kirish huquqiga ega</div>
    <a href="{% url 'home' %}" class="btn btn-outline-success mt-4">Bosh sahifaga qaytish</a>

    {% endif %}
</div>
{% endblock %}

home/templates/html/editAgent.html
{% extends 'html/base.html' %}
{% load static %}
{% block title %}Agents{% endblock %}

{% block content %}
<div class="editAgent containerCustom pt-2">
    {% if user.is_authenticated and isAdmin %}
    <div class="text-danger mb-2">{{errorr}}</div>
    <button type="button" class="btn btn-outline-warning" data-toggle="collapse" data-target="#changeMain">
        Asosiy qsimni o'zgartirish
    </button>
    <button type="button" class="btn btn-outline-danger ml-3" data-toggle="modal" data-target="#returnProductForm">
        Mahsulotni qaytarish
    </button> 

    <!-- The Modal -->
    <div class="modal baseModal" id="returnProductForm">
        <div class="modal-dialog">
            <div class="modal-content">
                <!-- Modal Header -->
                <div class="modal-header">
                    <h4 class="modal-title">Bazaga Mahsulot Qaytarish</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                    <form id="" action="{% url 'returnProductForSavod' formId %}" method="POST">
                        {% csrf_token %}
                        <input type="number" name="howMuch" class="form-control mb-3" placeholder="Qancha qaytarmoqchisiz ?">
                        
                        <div class="d-flex justify-content-between align-items-center">
                            <button type="submit" id="" class="btn btn-outline-dark">Qaytarish</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!-- The Row -->
    <div class="row mt-2 mb-5">
        <div class="col-md-6 mt-3">
            <div class="card collapse" id="changeMain">
                <div class="changed d-flex justify-content-end">
                    {% if agent.changed == True %}
                    <div class="badge badge-warning">
                        O'zgartirilgan
                    </div>
                    {% endif %}
                </div>
                <form id="enterForm" action="" method="POST">
                    {% csrf_token %}
                    <label for="id_typeOfProduct">Maxsulot turi</label><br>
                    {{form.typeOfProduct}}
                    <label for="id_kg">Kg</label><br>
                    {{form.kg}}
                    <label for="id_price">Sotilayotgan narxi</label><br>
                    {{form.price}}
                    <label for="id_totalSum">To'liq summasi</label><br>
                    {{form.totalSum}}
                    <label for="id_byWhom" class="">Kim tomonidan?</label><br>
                    {{form.byWhom}}
                    <div class="custom-control custom-switch mt-2">
                        {{form.debt}}
                        <label for="id_debt" class="custom-control-label">Yuk qarzga berilganmi?</label>
                    </div>
                    <div class="d-flex justify-content-between mt-3">
                        <button type="button" id="deleteBtn" class="btn btn-outline-danger"><img src="{% static 'delete.png' %}" class="w-30px" alt=""></button>
                        <button type="button" id="subBtn" class="btn btn-outline-dark">Saqlash</button>
                    </div>
                </form>
                <form action="{% url 'delete' formId %}" id="deleteForm" method="POST">
                    {% csrf_token %}
                </form>
            </div>
        </div>
        {% if agent.debt %}
        <div class="col-md-6 mt-3">
            <div class="card">
                <div class="mb-2 d-flex justify-content-between" id="totalLend">
                    {% if error %}
                    <div class="badge badge-danger">
                        {{error}}
                    </div>
                    {% endif %}
                    <div class="badge badge-success">
                        <span class="numMusk">{{totalLend}}</span> so'm to'lagan
                    </div>
                </div>
                <form id="postQarz" action="" method="POST">
                    {% csrf_token %}
                    <label for="id_qarzSum">Oxirgi marta bergan qarz summasi</label> <br>
                    {{form2.qarzSum}}
                    <label for="id_oxirgiQarzBerganVaqti">Oxirgi marta bergan qarz vaqti</label> <br>
                    {{form2.oxirgiQarzBerganVaqti}}
                    <div class="d-flex justify-content-end mt-3">
                        <button type="button" id="subBtnQarz" class="btn btn-outline-dark">Saqlash</button>
                    </div>
                </form>
                <script>
                    if (id_oxirgiQarzBerganVaqti.value == "1900-01-01") {
                        let d = new Date();
                        let arr = d.toLocaleDateString().split('/');
                        let month = (arr[0].length == 1) ? "0" + arr[0] : arr[0];
                        let day = (arr[1].length == 1) ? "0" + arr[1] : arr[1];
                        id_oxirgiQarzBerganVaqti.value = `${arr[2]}-${month}-${day}`;
                    } 
                    id_oxirgiQarzBerganVaqti.value = '';
                    id_qarzSum.value = '';
                </script>
            </div>
        </div>
        {% endif %}
    </div>
    {% endif %}
</div>
<style>
    footer {
        display: none;
    }
</style>
{% endblock %}